language: php
php:
- 7.1
env:
  matrix:
  - PHP_BIN=php
script:
- vendor/bin/tester -p $PHP_BIN tests -s
after_failure:
- for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
before_script:
- mkdir -p temp/cache
- mkdir log
- travis_retry composer install --no-interaction --prefer-dist
after_success:
- composer install --no-dev -o
- docker login -u $DHUSER -p "$DHPASS"
- docker build -t kozaktomas/sdhveselice:master .
- docker push kozaktomas/sdhveselice:master
sudo: required
services:
- docker
cache:
  directories:
  - "$HOME/.composer/cache"
dd:
  secure: PmBtnempHQ35NjavxVDvOVxZXdFx3U7WzlpGc+Fg/5IKV9753YlijagXkgkzDT/G1SZr1yKZXPjki92udwaSkzqBs05YAT27Ge9jXoyb4z4kAkrVVyJbD0uyOyhzXZkgRTx0HvrNcb760VL8MYytguL9ev6/IfANSygo1S/TDVzESvOb5oK/c7L7T0CQdDcFaa2NbQtcj16PwLqFYVfznqm0qgeJjLyxi1HropZXHbDqrotHipx2PXsygGoQlXGbyH0qwKWKyxAwk6TZ1ehjFfTvOqqMNi/hiW5kP7cvfqvK+O/wH+Ug/CtFLii9IlBph9vtqxk+wF+kRjhC6bViRI5eqjyfvk1hf3/7jJbQzKsSS+P+cxFK3RuFgqHMAlZl0lPbGenxDWZupdtiDuLcB6782thn/OzsP6KD+DgRvJ2Pc/0g28YF8FKoudx1UuHBPfRYl67++a9OrDE3fmD1rANpfZMl7q1hPbl9sG3KWv5AoTpF3uQt4K1BOyUeEoT+HSoktztFVYESiyxTQInEHcAT6DdU3HKhfDfpnijROz5+jth3eGg1YgByCmGeit1yuYQK3Ly7BmmA+4mYgbAWswcjbbBgF1UEBuOExPStrl+dJkVlOScY0GUzRIo0C5kH2+w2OLbvnSkwEfPhAwswyb/bMEWPeYA/4Gt3r0NTge4=
